declare module 'winapi-bindings' {
  export function GetVolumePathNamesForVolumeName(volumeName: string): string[];
  export function GetVolumeInformation(rootPath: string): any;
  export function GetDiskFreeSpaceEx(directoryName: string): any;
  export function ShellExecuteEx(executeInfo: any): any;
  export function GetModuleFileName(hModule: any): string;
  export function GetSystemDirectory(): string;
  export function GetWindowsDirectory(): string;
  export function RegOpenKeyEx(hKey: any, subKey: string, options: number, samDesired: number): any;
  export function RegQueryValueEx(hKey: any, valueName: string): any;
  export function RegCloseKey(hKey: any): void;
  export function RegEnumKeyEx(hKey: any, index: number): string;
  export function RegEnumValue(hKey: any, index: number): any;
  export function CreateProcess(applicationName: string, commandLine: string, processAttributes: any, threadAttributes: any, inheritHandles: boolean, creationFlags: number, environment: any, currentDirectory: string, startupInfo: any): any;
  export function WaitForSingleObject(handle: any, milliseconds: number): number;
  export function CloseHandle(handle: any): boolean;
  export function TerminateProcess(handle: any, exitCode: number): boolean;
  export function GetExitCodeProcess(handle: any): number;
  export function IsUserAnAdmin(): boolean;
  export function SetDllDirectory(pathName: string): boolean;
  export function LoadLibrary(fileName: string): any;
  export function FreeLibrary(hModule: any): boolean;
  export function GetProcAddress(hModule: any, procName: string): any;
  export function GetLastError(): number;
  export function FormatMessage(flags: number, source: any, messageId: number, languageId: number, buffer: any, size: number, args: any): number;
  export function GetCurrentProcess(): any;
  export function OpenProcessToken(processHandle: any, desiredAccess: number): any;
  export function GetTokenInformation(tokenHandle: any, tokenInformationClass: number): any;
  export function LookupAccountSid(systemName: string, sid: any): any;
  export function ConvertSidToStringSid(sid: any): string;
  export function ConvertStringSidToSid(stringSid: string): any;
  export function EqualSid(sid1: any, sid2: any): boolean;
  export function CopySid(destinationSid: any, sourceSid: any): boolean;
  export function GetLengthSid(sid: any): number;
  export function IsValidSid(sid: any): boolean;
  export function CreateWellKnownSid(wellKnownSidType: number, domainSid: any): any;
  export function CheckTokenMembership(tokenHandle: any, sidToCheck: any): boolean;
  export function DuplicateToken(existingTokenHandle: any, impersonationLevel: number): any;
  export function SetThreadToken(thread: any, token: any): boolean;
  export function RevertToSelf(): boolean;
  export function ImpersonateLoggedOnUser(token: any): boolean;
  export function LogonUser(username: string, domain: string, password: string, logonType: number, logonProvider: number): any;
  export function CreateProcessAsUser(token: any, applicationName: string, commandLine: string, processAttributes: any, threadAttributes: any, inheritHandles: boolean, creationFlags: number, environment: any, currentDirectory: string, startupInfo: any): any;
  export function CreateProcessWithLogonW(username: string, domain: string, password: string, logonFlags: number, applicationName: string, commandLine: string, creationFlags: number, environment: any, currentDirectory: string, startupInfo: any): any;
  export function CreateProcessWithTokenW(token: any, logonFlags: number, applicationName: string, commandLine: string, creationFlags: number, environment: any, currentDirectory: string, startupInfo: any): any;
  export function GetUserName(): string;
  export function GetComputerName(): string;
  export function GetSystemMetrics(index: number): number;
  export function GetSystemInfo(): any;
  export function GetVersionEx(): any;
  export function GetNativeSystemInfo(): any;
  export function IsWow64Process(processHandle: any): boolean;
  export function GetCurrentProcessId(): number;
  export function GetCurrentThreadId(): number;
  export function GetProcessId(processHandle: any): number;
  export function GetThreadId(threadHandle: any): number;
  export function OpenProcess(desiredAccess: number, inheritHandle: boolean, processId: number): any;
  export function OpenThread(desiredAccess: number, inheritHandle: boolean, threadId: number): any;
  export function SuspendThread(threadHandle: any): number;
  export function ResumeThread(threadHandle: any): number;
  export function GetThreadContext(threadHandle: any): any;
  export function SetThreadContext(threadHandle: any, context: any): boolean;
  export function GetProcessTimes(processHandle: any): any;
  export function GetThreadTimes(threadHandle: any): any;
  export function GetProcessMemoryInfo(processHandle: any): any;
  export function GetProcessWorkingSetSize(processHandle: any): any;
  export function SetProcessWorkingSetSize(processHandle: any, minimumWorkingSetSize: number, maximumWorkingSetSize: number): boolean;
  export function VirtualAlloc(address: any, size: number, allocationType: number, protect: number): any;
  export function VirtualFree(address: any, size: number, freeType: number): boolean;
  export function VirtualProtect(address: any, size: number, newProtect: number): any;
  export function VirtualQuery(address: any): any;
  export function ReadProcessMemory(processHandle: any, baseAddress: any, buffer: any, size: number): any;
  export function WriteProcessMemory(processHandle: any, baseAddress: any, buffer: any, size: number): any;
  export function FlushInstructionCache(processHandle: any, baseAddress: any, size: number): boolean;
  export function CreateRemoteThread(processHandle: any, threadAttributes: any, stackSize: number, startAddress: any, parameter: any, creationFlags: number): any;
  export function GetModuleHandle(moduleName: string): any;
  export function GetProcAddress(hModule: any, procName: string): any;
  export function LoadLibrary(fileName: string): any;
  export function FreeLibrary(hModule: any): boolean;
  export function GetModuleInformation(processHandle: any, hModule: any): any;
  export function EnumProcessModules(processHandle: any): any[];
  export function GetModuleFileNameEx(processHandle: any, hModule: any): string;
  export function GetModuleBaseName(processHandle: any, hModule: any): string;
  export function QueryFullProcessImageName(processHandle: any, flags: number): string;
  export function EnumProcesses(): number[];
  export function Process32First(snapshotHandle: any): any;
  export function Process32Next(snapshotHandle: any): any;
  export function CreateToolhelp32Snapshot(flags: number, processId: number): any;
  export function Thread32First(snapshotHandle: any): any;
  export function Thread32Next(snapshotHandle: any): any;
  export function Module32First(snapshotHandle: any): any;
  export function Module32Next(snapshotHandle: any): any;
  export function Heap32ListFirst(snapshotHandle: any): any;
  export function Heap32ListNext(snapshotHandle: any): any;
  export function Heap32First(snapshotHandle: any, processId: number, heapId: number): any;
  export function Heap32Next(snapshotHandle: any): any;
  export function GetSystemTimes(): any;
  export function GetTickCount(): number;
  export function GetTickCount64(): number;
  export function QueryPerformanceCounter(): any;
  export function QueryPerformanceFrequency(): any;
  export function Sleep(milliseconds: number): void;
  export function SleepEx(milliseconds: number, alertable: boolean): number;
  export function WaitForSingleObject(handle: any, milliseconds: number): number;
  export function WaitForSingleObjectEx(handle: any, milliseconds: number, alertable: boolean): number;
  export function WaitForMultipleObjects(handles: any[], waitAll: boolean, milliseconds: number): number;
  export function WaitForMultipleObjectsEx(handles: any[], waitAll: boolean, milliseconds: number, alertable: boolean): number;
  export function CreateEvent(eventAttributes: any, manualReset: boolean, initialState: boolean, name: string): any;
  export function OpenEvent(desiredAccess: number, inheritHandle: boolean, name: string): any;
  export function SetEvent(eventHandle: any): boolean;
  export function ResetEvent(eventHandle: any): boolean;
  export function PulseEvent(eventHandle: any): boolean;
  export function CreateMutex(mutexAttributes: any, initialOwner: boolean, name: string): any;
  export function OpenMutex(desiredAccess: number, inheritHandle: boolean, name: string): any;
  export function ReleaseMutex(mutexHandle: any): boolean;
  export function CreateSemaphore(semaphoreAttributes: any, initialCount: number, maximumCount: number, name: string): any;
  export function OpenSemaphore(desiredAccess: number, inheritHandle: boolean, name: string): any;
  export function ReleaseSemaphore(semaphoreHandle: any, releaseCount: number): any;
  export function CreateWaitableTimer(timerAttributes: any, manualReset: boolean, name: string): any;
  export function OpenWaitableTimer(desiredAccess: number, inheritHandle: boolean, name: string): any;
  export function SetWaitableTimer(timerHandle: any, dueTime: any, period: number, completionRoutine: any, argToCompletionRoutine: any, resume: boolean): boolean;
  export function CancelWaitableTimer(timerHandle: any): boolean;
  export function CreateFile(fileName: string, desiredAccess: number, shareMode: number, securityAttributes: any, creationDisposition: number, flagsAndAttributes: number, templateFile: any): any;
  export function ReadFile(fileHandle: any, buffer: any, numberOfBytesToRead: number): any;
  export function WriteFile(fileHandle: any, buffer: any, numberOfBytesToWrite: number): any;
  export function SetFilePointer(fileHandle: any, distanceToMove: number, distanceToMoveHigh: any, moveMethod: number): number;
  export function SetFilePointerEx(fileHandle: any, distanceToMove: any, newFilePointer: any, moveMethod: number): boolean;
  export function GetFileSize(fileHandle: any): any;
  export function GetFileSizeEx(fileHandle: any): any;
  export function GetFileType(fileHandle: any): number;
  export function GetFileInformationByHandle(fileHandle: any): any;
  export function GetFileInformationByHandleEx(fileHandle: any, fileInformationClass: number): any;
  export function SetFileInformationByHandle(fileHandle: any, fileInformationClass: number, fileInformation: any): boolean;
  export function FlushFileBuffers(fileHandle: any): boolean;
  export function GetTempPath(): string;
  export function GetTempFileName(pathName: string, prefixString: string, unique: number): string;
  export function GetCurrentDirectory(): string;
  export function SetCurrentDirectory(pathName: string): boolean;
  export function GetFullPathName(fileName: string): string;
  export function GetShortPathName(longPath: string): string;
  export function GetLongPathName(shortPath: string): string;
  export function CreateDirectory(pathName: string, securityAttributes: any): boolean;
  export function CreateDirectoryEx(templateDirectory: string, newDirectory: string, securityAttributes: any): boolean;
  export function RemoveDirectory(pathName: string): boolean;
  export function DeleteFile(fileName: string): boolean;
  export function CopyFile(existingFileName: string, newFileName: string, failIfExists: boolean): boolean;
  export function CopyFileEx(existingFileName: string, newFileName: string, progressRoutine: any, data: any, cancel: any, copyFlags: number): boolean;
  export function MoveFile(existingFileName: string, newFileName: string): boolean;
  export function MoveFileEx(existingFileName: string, newFileName: string, flags: number): boolean;
  export function MoveFileWithProgress(existingFileName: string, newFileName: string, progressRoutine: any, data: any, flags: number): boolean;
  export function ReplaceFile(replacedFileName: string, replacementFileName: string, backupFileName: string, replaceFlags: number, exclude: any, reserved: any): boolean;
  export function GetFileAttributes(fileName: string): number;
  export function GetFileAttributesEx(fileName: string, infoLevelId: number): any;
  export function SetFileAttributes(fileName: string, fileAttributes: number): boolean;
  export function GetCompressedFileSize(fileName: string): any;
  export function CompressFile(fileName: string): boolean;
  export function DecompressFile(fileName: string): boolean;
  export function FindFirstFile(fileName: string): any;
  export function FindFirstFileEx(fileName: string, infoLevelId: number, searchOp: number): any;
  export function FindNextFile(findHandle: any): any;
  export function FindClose(findHandle: any): boolean;
  export function GetDriveType(rootPathName: string): number;
  export function GetLogicalDrives(): number;
  export function GetLogicalDriveStrings(): string[];
  export function QueryDosDevice(deviceName: string): string[];
  export function DefineDosDevice(flags: number, deviceName: string, targetPath: string): boolean;
  export function GetVolumeInformation(rootPathName: string): any;
  export function SetVolumeLabel(rootPathName: string, volumeName: string): boolean;
  export function GetVolumePathName(fileName: string): string;
  export function GetVolumePathNamesForVolumeName(volumeName: string): string[];
  export function GetVolumeNameForVolumeMountPoint(volumeMountPoint: string): string;
  export function SetVolumeMountPoint(volumeMountPoint: string, volumeName: string): boolean;
  export function DeleteVolumeMountPoint(volumeMountPoint: string): boolean;
  export function FindFirstVolume(): any;
  export function FindNextVolume(findHandle: any): any;
  export function FindVolumeClose(findHandle: any): boolean;
  export function FindFirstVolumeMountPoint(rootPathName: string): any;
  export function FindNextVolumeMountPoint(findHandle: any): any;
  export function FindVolumeMountPointClose(findHandle: any): boolean;
  export function GetDiskFreeSpace(rootPathName: string): any;
  export function GetDiskFreeSpaceEx(directoryName: string): any;
  export function SetFileValidData(fileHandle: any, validDataLength: any): boolean;
  export function SetFileShortName(fileHandle: any, shortName: string): boolean;
  export function SetFileTime(fileHandle: any, creationTime: any, lastAccessTime: any, lastWriteTime: any): boolean;
  export function GetFileTime(fileHandle: any): any;
  export function FileTimeToSystemTime(fileTime: any): any;
  export function SystemTimeToFileTime(systemTime: any): any;
  export function FileTimeToLocalFileTime(fileTime: any): any;
  export function LocalFileTimeToFileTime(localFileTime: any): any;
  export function CompareFileTime(fileTime1: any, fileTime2: any): number;
  export function GetSystemTime(): any;
  export function GetLocalTime(): any;
  export function SetSystemTime(systemTime: any): boolean;
  export function SetLocalTime(localTime: any): boolean;
  export function GetSystemTimeAsFileTime(): any;
  export function GetTimeZoneInformation(): any;
  export function SetTimeZoneInformation(timeZoneInformation: any): boolean;
  export function SystemTimeToTzSpecificLocalTime(timeZoneInformation: any, universalTime: any): any;
  export function TzSpecificLocalTimeToSystemTime(timeZoneInformation: any, localTime: any): any;
  export function GetTimeFormat(locale: number, flags: number, time: any, format: string): string;
  export function GetDateFormat(locale: number, flags: number, date: any, format: string): string;
  export function GetNumberFormat(locale: number, flags: number, value: string, format: any): string;
  export function GetCurrencyFormat(locale: number, flags: number, value: string, format: any): string;
  export function GetUserDefaultLCID(): number;
  export function GetSystemDefaultLCID(): number;
  export function GetUserDefaultLangID(): number;
  export function GetSystemDefaultLangID(): number;
  export function GetLocaleInfo(locale: number, lcType: number): string;
  export function SetLocaleInfo(locale: number, lcType: number, data: string): boolean;
  export function EnumSystemLocales(flags: number): string[];
  export function IsValidLocale(locale: number, flags: number): boolean;
  export function ConvertDefaultLocale(locale: number): number;
  export function GetThreadLocale(): number;
  export function SetThreadLocale(locale: number): boolean;
  export function GetStringTypeEx(locale: number, infoType: number, srcStr: string): number[];
  export function LCMapString(locale: number, mapFlags: number, srcStr: string): string;
  export function GetACP(): number;
  export function GetOEMCP(): number;
  export function GetCPInfo(codePage: number): any;
  export function GetCPInfoEx(codePage: number, flags: number): any;
  export function IsValidCodePage(codePage: number): boolean;
  export function MultiByteToWideChar(codePage: number, flags: number, multiByteStr: string, cchWideChar: number): string;
  export function WideCharToMultiByte(codePage: number, flags: number, wideCharStr: string, cbMultiByte: number, defaultChar: string, usedDefaultChar: any): string;
  export function IsDBCSLeadByte(testChar: number): boolean;
  export function IsDBCSLeadByteEx(codePage: number, testChar: number): boolean;
  export function CharToOem(src: string): string;
  export function CharToOemBuff(src: string, dst: string, dstLength: number): boolean;
  export function OemToChar(src: string): string;
  export function OemToCharBuff(src: string, dst: string, dstLength: number): boolean;
  export function CharUpper(str: string): string;
  export function CharUpperBuff(str: string, length: number): number;
  export function CharLower(str: string): string;
  export function CharLowerBuff(str: string, length: number): number;
  export function CharNext(str: string): string;
  export function CharPrev(start: string, str: string): string;
  export function IsCharAlpha(ch: string): boolean;
  export function IsCharAlphaNumeric(ch: string): boolean;
  export function IsCharUpper(ch: string): boolean;
  export function IsCharLower(ch: string): boolean;
}